version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  test:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run:
          name: install
          working_directory: 03_js
          command: npm i
      - run:
          name: test
          working_directory: 03_js
          command: npm run test:ci
workflows:
  test:
    jobs:
      - test
