version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  test:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "03_js/package-lock.json" }}
      - run:
          name: install
          working_directory: 03_js
          command: npm i
      - save_cache:
          key:  v1-deps-{{ checksum "03_js/package-lock.json" }}
          paths:
            - 03_js/node_modules
      - run:
          name: test
          working_directory: 03_js
          command: npm run test:ci
workflows:
  test:
    jobs:
      - test
